### ISSUE TITLE
Package entries nest inside of each other

### ISSUE THREAD

**Issue by amargherio** [shurcooL/Go-Package-Store#36]
When opening the tool inside a browser (in my case, Chrome v44.0.2369.0 dev, although it shouldn't make too much of a difference if you use another browser), the box for each package seems to nest inside the change list of the one above it. 

![Nesting packages](http://i.imgur.com/XTxujf8.png)

Watching the console output, I keep seeing the following block (repeats for each package it queries for)

```
2015/04/20 12:25:33 t.Execute: template: repo.html.tmpl:37:102: executing "repo.html.tmpl" at <.Comments>: can't evaluate field Comments in type presenter.Change
2015/04/20 12:25:33 http: multiple response.WriteHeader calls
```

**Comment by amargherio** [comment]
Hmm...it looks like it's not doing it anymore. I just updated to the most recent version, not sure what changed, but everything seems to be displaying correctly now.

Sorry for the erroneous issue, and thanks for building a great tool.

**Comment by shurcooL** [comment]
No problem! Glad it works now.

This likely happened because Go Package Store was out of date. Perhaps a version mismatch of the `Go-Package-Store` binary and assets folder. Updating to latest version should fix it, and as you noticed it has. If you run into any other issues, please feel welcome to let me know!
