### ISSUE TITLE
Support govendor file format.

### ISSUE THREAD

**Issue by captncraig** [shurcooL/Go-Package-Store#49]
I am using https://github.com/kardianos/govendor for my vendoring needs. It would be nice if Go-Package-Store could load my vendor file and check for updates. It should be almost identical to godeps mode, but with a slightly different json schema.

**Comment by shurcooL** [comment]
I think I can support that.

I'll have to familiarize myself with the https://github.com/kardianos/vendor-spec file format.

Is there a parser for that file format that I should use? Or is it so trivial that I should just implement it as unexpected code? /cc @kardianos

**Comment by captncraig** [comment]
I'm thinking it should just be a matter of unmarshalling to a slightly different json object from what you are using for godeps. It is just json.

**Comment by kardianos** [comment]
There is a helper package here:
https://godoc.org/github.com/kardianos/govendor/vendorfile

Mainly useful if you are writing as well as reading as it will preserve unknown fields when writing (as the spec requires).

**Comment by shurcooL** [comment]
@captncraig, can you point me to a sample project that has a govendor file, so I can test out this feature?

**Comment by kardianos** [comment]
bitbucket.org/kardianos/rdb

**Comment by shurcooL** [comment]
Thanks @kardianos.

I tried the following:

```bash
$ Go-Package-Store -govendor=.../src/bitbucket.org/kardianos/rdb/vendor/vendor.json
```

I see its vendor.json has:

```
{
	"path": "golang.org/x/net/context",
	"revision": "aa73292ff82e",
	"revisionTime": "2014-11-10T09:49:06+09:00"
}
```

But that commit doesn't exist in the current golang.org/x/net/context history:

https://github.com/golang/net/commit/aa73292ff82e

It does exist in the previous mercurial repo:

https://code.google.com/p/go/source/browse/?repo=net&r=aa73292ff82e

Go Package Store cannot compare version across different repositories in the general case, so you'll see this:

![image](https://cloud.githubusercontent.com/assets/1924134/11619993/12cbedac-9c63-11e5-8967-e780d40a935d.png)

However, it works well on the other two packages:

![image](https://cloud.githubusercontent.com/assets/1924134/11620040/97cb04ca-9c63-11e5-8d49-b1d36ae2e01e.png)

It looks like there have been a lot of updates to that repo since the last time you've updated it. :)

**Comment by kardianos** [comment]
Whoops! Oh, I think I had a bug in the tool when I added that. Will fix.

**Comment by kardianos** [comment]
I fixed the rdb repo. Should be able to test properly this time.

**Comment by shurcooL** [comment]
It works as expected. Your `golang.org/x/net/context` dependency is now up to date, and hence doesn't show up.

The other repo has a few new commits, and they show up.

![image](https://cloud.githubusercontent.com/assets/1924134/11644313/b4de7302-9cff-11e5-93a4-8672595457ae.png)

I'll be merging the PR soon. @captncraig, please try it out and let me know if it resolves your needs.

**Comment by shurcooL** [comment]
It's live now.

Do `go get -u github.com/shurcooL/Go-Package-Store` as always to update to latest version, and let me know @captncraig!
