### ISSUE TITLE
git fast forward failed caused package updated skipped

### ISSUE THREAD

**Issue by stardiviner** [shurcooL/Go-Package-Store#62]
Here is the output:
```
cd /home/stardiviner/.go/src/github.com/sourcegraph/srclib
git pull --ff-only# cd /home/stardiviner/.go/src/github.com/sourcegraph/srclib; git pull --ff-only
fatal: Not possible to fast-forward, aborting.

Done.
```
This invalid fast-forward caused package update failed.

**Comment by shurcooL** [comment]
Yes, this is normal. If a Go package can't be updated because its repository can't do a fast-forward git pull, then Go Package Store will print that message to stderr and not actually update the package successfully.

It behaves just like `go get` does.

When this happens, you'll need to carefully resolve the problem yourself and return the repo to a state where it can be fast-forwarded. Either do that by reseting it's master to origin/master, or remove the repo and `go get` it again.

One possible enhancement to Go Package Store is to display these errors in the frontend rather than stderr in console. That is an enhancement that may come later.

**Comment by stardiviner** [comment]
I see, thanks.
