### ISSUE TITLE
https://github.com and git@github.com equivalence

### ISSUE THREAD

**Issue by dmitris** [shurcooL/Go-Package-Store#65]
I'm seeing lots of messages like:

skipping "github.com/prometheus/prometheus" because:
	remote URL (git@github.com:prometheus/prometheus.git) doesn't match repo URL inferred from import path (https://github.com/prometheus/prometheus)

Would it be possible for the tool to realize that they are equivalent and follow the origin git@github.com:prometheus/prometheus.git?  The `go` tool seems to be able to handle it - I can do:
`go get -v -x github.com/prometheus/prometheus/...` even though my origin for `$GOPATH/src/github.com/prometheus/prometheus` is set to `git@github.com:prometheus/prometheus.git`, not `https://github.com/prometheus/prometheus`.

**Comment by shurcooL** [comment]
This issue is subtle. Let me explain what's going on.

The **actual** reason GPS currently prints that error is not because of the difference in scheme (git@github.com:... vs https://github.com/...). It correctly compares different schemes and considers them equivalent via [`status.EqualRepoURLs`](https://godoc.org/github.com/shurcooL/gostatus/status#EqualRepoURLs).

The reason it says they're different is because of the ".git" suffix that one URL has but the other doesn't.

Related issue:

https://github.com/shurcooL/gostatus/issues/37

You can read my detailed rationale for the behavior in https://github.com/shurcooL/gostatus/issues/37#issuecomment-225336823. @mafredri came up with a nice way to quickly fix the problem in his GOPATH in https://github.com/shurcooL/gostatus/issues/37#issuecomment-225350473.

Another highly related issue is:

https://github.com/shurcooL/gostatus/issues/39

Which I think definitely played a role here, and I should try to fix it.

However, the fact that `go get -u` works suggests I may want to consider being less strict and also allow it. I'll look into that. However, I worry that the reason `go get -u` works might be because it doesn't check the remote URL at all. That would mean you could get arbitrary updates from odd remote URLs. I would feel nervous about allowing that. Anyway, I'll check, it might be that `go get -u` has code to ignore a ".git" suffix only.

**Comment by shurcooL** [comment]
This is sad, but `go get -u` will just do `git pull --ff-only` and it doesn't care what remote URL is. It'll happily pull from something other than what the user would get if they did `git get -u import/path` in an empty GOPATH.

**Comment by shurcooL** [comment]
I've resolved shurcooL/gostatus#39 and applied the fix to Go Package Store in 12c0a37f04d98796fc7242baa7e13cc77ce453ea.

Hopefully that helps.

**Comment by shurcooL** [comment]
I consider 12c0a37f04d98796fc7242baa7e13cc77ce453ea to have resolved this issue. I will look into `go get -u` behavior separately (I think it has room for improvement).

Closing, let me know if you have any further comments.
